- 👋 Hi, I’m Soressa Dima
- 👀 I'm interested in coding and problem solving.
- 🌱 I’m currently learning Computer Science
- 💞️ I’m looking to collaborate on Web Development
- 📫 How to reach me soressadima98gmail.com
